-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-24 15:18:57 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE location_chief (
    staff_id       NUMBER NOT NULL,
    location_code  VARCHAR2(50) NOT NULL
);

ALTER TABLE location_chief ADD CONSTRAINT chief_staff_unique UNIQUE ( staff_id );

ALTER TABLE location_chief ADD CONSTRAINT chief_location_unique UNIQUE ( location_code );

CREATE TABLE locations (
    location_name VARCHAR2(50) NOT NULL
);

ALTER TABLE locations ADD CONSTRAINT locations_pk PRIMARY KEY ( location_name );

CREATE TABLE staff (
    id          NUMBER NOT NULL,
    first_name  VARCHAR2(15)
);

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( id );

CREATE TABLE weather_daily (
    weather_date       DATE NOT NULL,
    location_code      VARCHAR2(50) NOT NULL,
    rainfall           NUMBER(5, 2),
    evaporation        NUMBER(5, 2),
    sunshine           NUMBER(5, 2),
    wind_gust_dir      VARCHAR2(3) NOT NULL,
    wind_gust_speed    NUMBER(5, 2),
    rainfall_tomorrow  NUMBER(5, 2)
);

ALTER TABLE weather_daily ADD CONSTRAINT daily_pk PRIMARY KEY ( location_code,
                                                                weather_date );

CREATE TABLE weather_hourly (
    location_code  VARCHAR2(50) NOT NULL,
    weather_date   DATE NOT NULL,
    time           NUMBER NOT NULL,
    wind_dir       VARCHAR2(3) NOT NULL,
    wind_speed     NUMBER(5, 2),
    humidity       NUMBER(3),
    pressure       NUMBER(10, 2),
    cloud          NUMBER,
    temperature    NUMBER(5, 2)
);

ALTER TABLE weather_hourly
    ADD CONSTRAINT hourly_pk PRIMARY KEY ( location_code,
                                           weather_date,
                                           time );

CREATE TABLE wind_direction (
    wind_direction VARCHAR2(3) NOT NULL
);

ALTER TABLE wind_direction ADD CONSTRAINT wind_direction_pk PRIMARY KEY ( wind_direction );

ALTER TABLE location_chief
    ADD CONSTRAINT chief_locations_fk FOREIGN KEY ( location_code )
        REFERENCES locations ( location_name );

ALTER TABLE location_chief
    ADD CONSTRAINT chief_staff_fk FOREIGN KEY ( staff_id )
        REFERENCES staff ( id );

ALTER TABLE weather_daily
    ADD CONSTRAINT daily_locations_fk FOREIGN KEY ( location_code )
        REFERENCES locations ( location_name );

ALTER TABLE weather_daily
    ADD CONSTRAINT daily_wind_dir_fk FOREIGN KEY ( wind_gust_dir )
        REFERENCES wind_direction ( wind_direction );

ALTER TABLE weather_hourly
    ADD CONSTRAINT hourly_daily_fk FOREIGN KEY ( location_code,
                                                 weather_date )
        REFERENCES weather_daily ( location_code,
                                   weather_date );

ALTER TABLE weather_hourly
    ADD CONSTRAINT hourly_wind_dir_fk FOREIGN KEY ( wind_dir )
        REFERENCES wind_direction ( wind_direction );

-- -------------------------
-- manually added constrains
-- --------------------------

ALTER TABLE WEATHER_HOURLY
ADD CONSTRAINT check_time
  CHECK (time >= 0 and time < 24);
           
ALTER TABLE LOCATIONS
ADD CONSTRAINT check_location_name
  CHECK (length(LOCATION_NAME) > 2);

ALTER TABLE STAFF
ADD CONSTRAINT check_employeer_name
  CHECK (length(FIRST_NAME) > 2);

ALTER TABLE WEATHER_DAILY
ADD CONSTRAINT check_date
  CHECK ( WEATHER_DATE >= to_date('2000-01-01', 'YYYY-mm-dd'));
  
CREATE SEQUENCE id_staff_seq INCREMENT BY 1 START WITH 1 MINVALUE 1;
